/*
* Generated file
*
* Generated from: yang module name: negotiator-impl yang module local name: negotiator-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Jun 04 19:02:40 EEST 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package eu.virtuwind.negotiator.impl;
public class NegotiatorModuleFactory extends eu.virtuwind.negotiator.impl.AbstractNegotiatorModuleFactory {

}
