/*
* Generated file
*
* Generated from: yang module name: monitoring-impl yang module local name: monitoring-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Jun 04 20:50:32 EEST 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package eu.virtuwind.monitoring.impl;
public class MonitoringModuleFactory extends eu.virtuwind.monitoring.impl.AbstractMonitoringModuleFactory {

}
