/*
* Generated file
*
* Generated from: yang module name: reference-impl yang module local name: reference-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Fri Jun 03 11:12:34 EEST 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package eu.virtuwind.reference.impl;
public class ReferenceModuleFactory extends eu.virtuwind.reference.impl.AbstractReferenceModuleFactory {

}
